### ISSUE TITLE
Failed to patch and failed to select custom app/package name in CLI menu

### ISSUE THREAD

**Issue by mdsdtech** [decipher3114/Revancify#12]
![Screenshot_2023-08-28-16-44-55-498_com termux](https://github.com/decipher3114/Revancify/assets/70020155/ef8dcddc-72ca-4dd9-8e3f-f4a0d0e5abc4)

Patch Log:
```
INFO: Loading patches 
INFO: Setting patch options 
com.fasterxml.jackson.databind.exc.MismatchedInputException: No content to map due to end-of-input
 at [Source: (String)""; line: 1, column: 0]
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:4821)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4723)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3677)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3645)
	at app.revanced.utils.Options.deserialize(Options.kt:52)
	at app.revanced.utils.Options.setOptions(Options.kt:63)
	at app.revanced.utils.Options.setOptions(Options.kt:89)
	at app.revanced.cli.command.PatchCommand.run(PatchCommand.kt:163)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at app.revanced.cli.command.MainCommandKt.main(MainCommand.kt:40)



Rooted: false
Arch: arm64-v8a
App: YouTube v18.33.37
CLI: revanced-cli-v3.0.0.jar
Patches: YT-Advanced-patches-v2.189.1.jar
Integrations: YT-Advanced-integrations-v0.117.3.apk
Patches argument: -i alternative-thumbnails
-i bypass-ambient-mode-restrictions
-i change-homepage
-i custom-branding-youtube-name
-i custom-double-tap-length
-i custom-package-name
-i custom-playback-speed
-i custom-seekbar-color
-i default-playback-speed
-i default-video-quality
-i disable-quic-protocol
-i disable-shorts-on-startup
-i disable-auto-captions
-i disable-haptic-feedback
-i disable-hdr-video
-i disable-pip-notification
-i enable-compact-controls-overlay
-i enable-external-browser
-i enable-minimized-playback
-i enable-new-comment-popup-panels
-i enable-new-splash-animation
-i enable-new-thumbnail-preview
-i enable-old-quality-layout
-i enable-open-links-directly
-i enable-seekbar-tapping
-i enable-tablet-mini-player
-i enable-tablet-navigation-bar
-i enable-time-stamps-speed
-i enable-wide-search-bar
-i force-opus-codec
-i force-vp9-codec
-i force-premium-heading
-i header-switch
-i hide-account-menu
-i hide-auto-player-popup-panels
-i hide-autoplay-button
-i hide-autoplay-preview
-i hide-button-container
-i hide-captions-button
-i hide-cast-button
-i hide-category-bar
-i hide-channel-avatar-section
-i hide-channel-watermark
-i hide-collapse-button
-i hide-comment-component
-i hide-crowdfunding-box
-i hide-description-components
-i hide-end-screen-cards
-i hide-end-screen-overlay
-i hide-feed-flyout-panel
-i hide-filmstrip-overlay
-i hide-floating-microphone
-i hide-fullscreen-panels
-i hide-general-ads
-i hide-handle
-i hide-info-cards
-i hide-latest-videos-button
-i hide-layout-components
-i hide-load-more-button
-i hide-mix-playlists
-i hide-music-button
-i hide-navigation-buttons
-i hide-navigation-label
-i hide-player-button-background
-i hide-player-flyout-panel
-i hide-player-overlay-filter
-i hide-previous-next-button
-i hide-quick-actions
-i hide-seek-message
-i hide-seekbar
-i hide-shorts-components
-i hide-snack-bar
-i hide-speed-overlay
-i hide-suggested-actions
-i hide-suggested-video-overlay
-i hide-suggestions-shelf
-i hide-time-stamp
-i hide-tooltip-content
-i hide-trending-searches
-i hide-video-ads
-i language-switch
-i layout-switch
-i microg-support
-i overlay-buttons
-i return-youtube-dislike
-i settings
-i sponsorblock
-i spoof-app-version
-i spoof-player-parameters
-i swipe-controls
-i theme
-i translations
```

**Comment by decipher3114** [comment]
Delete patch options and repatch.
