### ISSUE TITLE
Can't patch twitter

### ISSUE THREAD

**Issue by JimZiii** [decipher3114/Revancify#150]
I've patched twitter a while back but for some reason it now fails every time i try to patch it, even when i try to patch the same version I've previously patched and currently running. 
Also, opening "select patches" for twitter seems to break the revacify script and you're instantly out in the regular command line.
reinstalling your script.

This is the patchlog.txt
```
Exception in thread "main" kotlin.jvm.KotlinReflectionNotSupportedError: Kotlin reflection implementation is not found at runtime. Make sure you have kotlin-reflect.jar in the classpath
	at kotlin.jvm.internal.ClassReference.error(ClassReference.kt:88)
	at kotlin.jvm.internal.ClassReference.getNestedClasses(ClassReference.kt:24)
	at kotlin.reflect.full.KClasses.getCompanionObject(KClasses.kt:47)
	at app.revanced.patcher.extensions.PatchExtensions.getOptions(AnnotationExtensions.kt:62)
	at app.revanced.utils.OptionsLoader.generateDefaults(OptionsLoader.kt:68)
	at app.revanced.utils.OptionsLoader.init(OptionsLoader.kt:25)
	at app.revanced.cli.command.MainCommand.run(MainCommand.kt:137)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at app.revanced.cli.main.MainKt.main(Main.kt:7)



Variant: nonroot
Arch: arm64
App: Twitter-9.65.5-release.0.apk

**Comment by decipher3114** [comment]
I will surely check this.

**Comment by decipher3114** [comment]
Fixed it in the latest commit
