### ISSUE TITLE
Revanify YouTube Issue

### ISSUE THREAD

**Issue by TheGoldenSun** [decipher3114/Revancify#155]
Hi decipher, I seem to be encountering an issue where I couldn't patch YouTube or any other applications on your revanify program because it'll always say: 

"Oops. Patching Failed !! 
Log file saved to revanify folder. 
Share the patchlog to developer" 

I tapped okay and it look me back into the main menu of revanify, this is worse since I can't fully update my integrations and patching on my arm64 inotia00 did for revanced extended users.

**Comment by decipher3114** [comment]
send the log please. Open file manager, go to Revancify folder in Internal storage and send the file patchlog.txt here.

**Comment by TheGoldenSun** [comment]
![Screenshot_20230112_235521](https://user-images.githubusercontent.com/104534608/212240687-0ef9969a-6a7e-4a50-8f7f-92ecbc7417d5.png)

@decipher3114

**Comment by TheGoldenSun** [comment]
@decipher3114 INFO: Reading dex files 
INFO: Decoding AndroidManifest.xml only, because resources are not needed 
INFO: Merging ./revanced-integrations-v0.92.2.apk 
java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at org.jf.dexlib2.util.DexUtil.verifyDexHeader(DexUtil.java:91)
	at lanchon.multidexlib2.RawDexIO.readRawDexFile(RawDexIO.java:53)
	at lanchon.multidexlib2.RawDexIO.readRawDexFile(RawDexIO.java:43)
	at lanchon.multidexlib2.MultiDexIO.readMultiDexContainer(MultiDexIO.java:66)
	at lanchon.multidexlib2.MultiDexIO.readMultiDexContainer(MultiDexIO.java:51)
	at lanchon.multidexlib2.MultiDexIO.readMultiDexContainer(MultiDexIO.java:42)
	at lanchon.multidexlib2.MultiDexIO.readDexFile(MultiDexIO.java:36)
	at app.revanced.patcher.Patcher.addFiles(Patcher.kt:85)
	at app.revanced.utils.patcher.PatcherKt.mergeFiles(Patcher.kt:72)
	at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:16)
	at app.revanced.cli.command.MainCommand.run(MainCommand.kt:155)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at app.revanced.cli.main.MainKt.main(Main.kt:7)



Variant: nonroot
Arch: arm64
App: YouTube-17.49.37.apk

**Comment by decipher3114** [comment]
use reinstall command, i guess some files are not fully downloaded.

**Comment by decipher3114** [comment]
or update resources again and see if they are downloaded successfully

**Comment by decipher3114** [comment]
Fixed this issue now
