### ISSUE TITLE
Fails to patch youtube (Keystore does not contain alias ReVanced Key)

### ISSUE THREAD

**Issue by abosaad11** [decipher3114/Revancify#32]
I spent a while trying to patch any youtube version (old, new, root, non-root). Allattempts fail with the following error. I tried to have youtube already installed, or uninstalled. All the same result. Tried with youtube 18.38.44 and 18.32.39.

```
INFO: Loading patches 
INFO: Decoding app manifest 
INFO: External downloads excluded 
INFO: Copy video url excluded 
INFO: Disable fine scrubbing gesture excluded 
INFO: Seekbar tapping excluded 
INFO: Swipe controls excluded 
INFO: Hide ads excluded 
INFO: Video ads excluded 
INFO: Old video quality menu excluded 
INFO: Playback speed excluded 
INFO: HDR auto brightness excluded 
INFO: Remember video quality excluded 
INFO: Always autorepeat excluded 
INFO: Vanced MicroG support excluded 
INFO: Minimized playback excluded 
INFO: Disable zoom haptics excluded 
INFO: Enable debugging excluded 
INFO: Bypass URL redirects excluded 
INFO: Open links externally excluded 
INFO: Client spoof excluded 
INFO: Hide filter bar excluded 
INFO: Hide timestamp excluded 
INFO: Hide 'Load more' button excluded 
INFO: Hide layout components excluded 
INFO: Hide breaking news shelf excluded 
INFO: Hide endscreen cards excluded 
INFO: Hide floating microphone button excluded 
INFO: Hide watermark excluded 
INFO: Comments excluded 
INFO: Hide album cards excluded 
INFO: Hide email address excluded 
INFO: Hide seekbar excluded 
INFO: Hide Shorts components excluded 
INFO: Hide crowdfunding box excluded 
INFO: Hide info cards excluded 
INFO: Player flyout menu excluded 
INFO: Hide captions button excluded 
INFO: Hide autoplay button excluded 
INFO: Navigation buttons excluded 
INFO: Hide video action buttons excluded 
INFO: Hide cast button excluded 
INFO: Hide player buttons excluded 
INFO: Disable auto captions excluded 
INFO: Wide searchbar excluded 
INFO: Enable tablet layout excluded 
INFO: Disable Shorts on startup excluded 
INFO: Theme excluded 
INFO: Disable player popup panels excluded 
INFO: SponsorBlock excluded 
INFO: Custom branding excluded 
INFO: Premium heading excluded 
INFO: Return YouTube Dislike excluded 
INFO: Tablet mini player excluded 
INFO: Spoof app version excluded 
INFO: Alternative thumbnails excluded 
INFO: Custom player overlay opacity excluded 
INFO: Remove player controls background excluded 
INFO: Export all activities excluded 
INFO: Remove screen capture restriction excluded 
INFO: Remove screenshot restriction excluded 
INFO: Spoof Wi-Fi connection excluded 
INFO: Predictive back gesture excluded 
INFO: Override certificate pinning excluded 
INFO: Change package name excluded 
INFO: Enable Android debugging excluded 
INFO: Setting patch options 
INFO: Executing patches 
INFO: Compiling modified dex files 
INFO: Aligning base.apk 
java.lang.IllegalArgumentException: Keystore does not contain alias ReVanced Key
	at app.revanced.library.ApkSigner.readKeyCertificatePair(ApkSigner.kt:91)
	at app.revanced.library.ApkSigner.newApkSignerBuilder(ApkSigner.kt:228)
	at app.revanced.library.ApkUtils.sign(ApkUtils.kt:79)
	at app.revanced.cli.command.PatchCommand.run(PatchCommand.kt:246)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at app.revanced.cli.command.MainCommandKt.main(MainCommand.kt:13)



Rooted: true
Arch: arm64-v8a
App: YouTube v18.32.39
CLI: revanced-cli-v4.0.1.jar
Patches: revanced-patches-v2.193.0.jar
Integrations: revanced-integrations-v0.119.0.apk
Patches argument: -i external-downloads
-i copy-video-url
-i disable-fine-scrubbing-gesture
-i seekbar-tapping
-i swipe-controls
-i hide-ads
-i video-ads
-i old-video-quality-menu
-i playback-speed
-i hdr-auto-brightness
-i remember-video-quality
-i minimized-playback
-i disable-zoom-haptics
-i enable-debugging
-i bypass-url-redirects
-i open-links-externally
-i client-spoof
-i hide-filter-bar
-i hide-timestamp
-i hide-'load-more'-button
-i hide-layout-components
-i hide-breaking-news-shelf
-i hide-endscreen-cards
-i hide-floating-microphone-button
-i hide-watermark
-i comments
-i hide-album-cards
-i hide-email-address
-i hide-seekbar
-i hide-shorts-components
-i hide-crowdfunding-box
-i hide-info-cards
-i player-flyout-menu
-i hide-captions-button
-i hide-autoplay-button
-i navigation-buttons
-i hide-video-action-buttons
-i hide-cast-button
-i hide-player-buttons
-i disable-auto-captions
-i wide-searchbar
-i enable-tablet-layout
-i disable-shorts-on-startup
-i theme
-i disable-player-popup-panels
-i sponsorblock
-i premium-heading
-i return-youtube-dislike
-i tablet-mini-player
-i spoof-app-version
-i alternative-thumbnails
-i custom-player-overlay-opacity

```

**Comment by LambdaSoft** [comment]
Same here
