### ISSUE TITLE
YT-Advanced CLI Fail 03/04/24

### ISSUE THREAD

**Issue by omaralwardian** [decipher3114/Revancify#58]
Logfile attached per app request. 
[patch_log.txt](https://github.com/decipher3114/Revancify/files/14481078/patch_log.txt)

INFO: Loading patches 
java.util.zip.ZipException: invalid CEN header (bad signature)
	at java.base/java.util.zip.ZipFile$Source.zerror(ZipFile.java:1577)
	at java.base/java.util.zip.ZipFile$Source.checkAndAddEntry(ZipFile.java:1165)
	at java.base/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1517)
	at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1297)
	at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1259)
	at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:708)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:242)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:172)
	at java.base/java.util.jar.JarFile.<init>(JarFile.java:347)
	at java.base/java.util.jar.JarFile.<init>(JarFile.java:318)
	at java.base/java.util.jar.JarFile.<init>(JarFile.java:284)
	at app.revanced.patcher.PatchBundleLoader$Jar$2.invoke(PatchBundleLoader.kt:106)
	at app.revanced.patcher.PatchBundleLoader$Jar$2.invoke(PatchBundleLoader.kt:105)
	at app.revanced.patcher.PatchBundleLoader.<init>(PatchBundleLoader.kt:140)
	at app.revanced.patcher.PatchBundleLoader.<init>(PatchBundleLoader.kt)
	at app.revanced.patcher.PatchBundleLoader.<init>(PatchBundleLoader.kt:34)
	at app.revanced.patcher.PatchBundleLoader$Jar.<init>(PatchBundleLoader.kt:102)
	at app.revanced.cli.command.PatchCommand.run(PatchCommand.kt:259)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at app.revanced.cli.command.MainCommandKt.main(MainCommand.kt:12)

**Comment by pmsobrado** [comment]
Same issue here, was working a couple of days ago. I did update Play Integrity Fix yesterday afternoon, maybe it's related?

**Comment by omaralwardian** [comment]
Resolved in later patches.
