### ISSUE TITLE
Error when patching Messenger. OpenJDK17 problem?

### ISSUE THREAD

**Issue by Blazko381** [decipher3114/Revancify#70]
Error occurred during initialization of VM
Unable to load native library: dlopen failed: library "libandroid-spawn.so" not found: needed by /data/data/com.termux/files/usr/lib/jvm/java-17-openjdk/lib/libjava.so in namespace (default)

Rooted: false
Arch: arm64-v8a
App: Messenger v451.1.0.59.109
CLI: revanced-cli-v4.5.0.jar
Patches: revanced-patches-v4.5.0.jar
Integrations: revanced-integrations-v1.7.0.apk
Patches argument: -i Hide inbox ads

**Comment by dutuka** [comment]
I have the same issue, any solution?

**Comment by Fivesal** [comment]
Same🙋

**Comment by Blazko381** [comment]
Problem is with libraries latest openjdk17. Help only:
pkg remove openjdk-17 -y && apt autoremove -y && pkg install openjdk-17 wget ncurses-utils dialog pup jq -y && apt install libandroid-spawn

**Comment by dutuka** [comment]
@Blazko381 i run your command and try to patch again, i got a new error:

`INFO: Loading patches 
INFO: Decoding app manifest 
INFO: Change player flyout panel toggles excluded 
INFO: Disable landscape mode excluded 
INFO: Hide animated button background excluded 
INFO: Hide double tap to like animations excluded 
INFO: Hide double tap overlay filter excluded 
INFO: MaterialYou excluded 
INFO: Add splash animation excluded 
INFO: Hide voice search button excluded 
INFO: Enable debug logging excluded 
INFO: Hide player chapters excluded 
INFO: Hide fullscreen button excluded 
INFO: Hide player button background excluded 
INFO: Shorts outline button excluded 
INFO: Spoof player parameters excluded 
INFO: Setting patch options 
com.fasterxml.jackson.databind.exc.MismatchedInputException: No content to map due to end-of-input
 at [Source: REDACTED (`StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION` disabled); line: 1]
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:4990)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4892)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3846)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3814)
	at app.revanced.library.Options.deserialize(Options.kt:64)
	at app.revanced.library.Options.setOptions(Options.kt:76)
	at app.revanced.library.Options.setOptions(Options.kt:100)
	at app.revanced.cli.command.PatchCommand.run(PatchCommand.kt:289)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at app.revanced.cli.command.MainCommandKt.main(MainCommand.kt:12)



Rooted: false
Arch: arm64-v8a
App: YouTube v19.07.40
CLI: inotia00-cli-v4.4.1.jar
Patches: YT-Advanced-patches-v2.220.10.jar
Integrations: YT-Advanced-integrations-v0.148.4.apk
Patches argument: -i Alternative thumbnails -i Ambient mode switch -i Append time stamps information -i Change start page -i Custom branding heading -i Custom branding icon YouTube -i Custom branding name YouTube -i Custom double tap length -i Custom package name -i Custom playback speed -i Custom player overlay opacity -i Custom seekbar color -i Default playback speed -i Default video quality -i Disable HDR video -i Disable QUIC protocol -i Disable auto captions -i Disable haptic feedback -i Disable pip notification -i Disable rolling number animations -i Disable shorts on startup -i Disable speed overlay -i Disable update screen -i Enable bottom player gestures -i Enable compact controls overlay -i Enable external browser -i Enable gradient loading screen -i Enable language switch -i Enable minimized playback -i Enable new splash animation -i Enable new thumbnail preview -i Enable old quality layout -i Enable open links directly -i Enable seekbar tapping -i Enable song search -i Enable tablet mini player -i Enable tablet navigation bar -i Enable wide search bar -i Force fullscreen -i Force opus codec -i Force video codec -i Hide account menu -i Hide auto player popup panels -i Hide autoplay button -i Hide autoplay preview -i Hide button container -i Hide captions button -i Hide cast button -i Hide category bar -i Hide channel avatar section -i Hide channel profile components -i Hide channel watermark -i Hide collapse button -i Hide comment component -i Hide crowdfunding box -i Hide description components -i Hide end screen cards -i Hide end screen overlay -i Hide feed flyout panel -i Hide filmstrip overlay -i Hide floating microphone -i Hide fullscreen panels -i Hide general ads -i Hide handle -i Hide info cards -i Hide latest videos button -i Hide layout components -i Hide load more button -i Hide mix playlists -i Hide music button -i Hide navigation buttons -i Hide navigation label -i Hide player flyout panel -i Hide previous next button -i Hide search term thumbnail -i Hide seek message -i Hide seekbar -i Hide shorts components -i Hide snack bar -i Hide suggested actions -i Hide suggested video overlay -i Hide suggestions shelf -i Hide time stamp -i Hide toolbar button -i Hide tooltip content -i Hide trending searches -i Hide video ads -i Keep landscape mode -i Layout switch -i MicroG support -i Overlay buttons -i Quick actions components -i Remove viewer discretion dialog -i Return YouTube Dislike -i Sanitize sharing links -i Settings -i SponsorBlock -i Spoof app version -i Spoof device dimensions -i Swipe controls -i Theme -i Translations`

**Comment by Blazko381** [comment]
You must clear data of Termux Monet and install again revancify. I use anddea patches, because are the best.

**Comment by dutuka** [comment]
Thank you for your help, i cleared Termux  data and use anddea patches, it worked for me.

**Comment by geraniumblessing** [comment]
I just ran into this issue. Fixed it by running `pkg install libandroid-spawn` first.

[libandroid-spawn](https://github.com/termux/termux-packages/blob/master/packages/libandroid-spawn/build.sh) is a termux package. You can install termux packages via [`pkg install <package-name>`](https://wiki.termux.com/wiki/Package_Management#Using_the_package_manager).
