### ISSUE TITLE
Patch YM error

### ISSUE THREAD

**Issue by mesofranico** [decipher3114/Revancify#90]
Patching YouTubeMusic...                                Exception in thread "main" java.lang.NoClassDefFoundError: app/revanced/patcher/patch/impl/BytecodePatch                at java.base/java.lang.ClassLoader.defineClass1(Native Method)                                                  at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)                                           at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
        at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:519)                                       at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:427)                                             at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:421)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:420)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        at app.revanced.patcher.util.patch.PatchBundle.loadPatches$revanced_patcher(PatchBundle.kt:20)
        at app.revanced.patcher.util.patch.PatchBundle$Jar.loadPatches(PatchBundle.kt:38)                               at app.revanced.cli.command.MainCommand.run(MainCommand.kt:134)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
        at picocli.CommandLine$RunLast.handle(CommandLin
           █▀█ █▀▀ █░█ ▄▀█ █▄░█ █▀▀ █ █▀▀ █▄█
           █▀▄ ██▄ ▀▄▀ █▀█ █░▀█ █▄▄ █ █▀░ ░█░

e.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at app.revanced.cli.main.MainKt.main(Main.kt:7)
Caused by: java.lang.ClassNotFoundException: app.revanced.patcher.patch.impl.BytecodePatch
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:440)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        ... 22 more
Unmounting YouTube Music...
Please wait...
This may take some time.
Success
cp: bad '/data/data/com.termux/files/home/storage/Revancify/YouTubeMusicRevanced-5.26.52.apk': No such file or directory
Mounting YouTube Music Revanced ...
kill: no process ID specified
Try 'kill --help' for more information.
~/storage/Revancify $

**Comment by decipher3114** [comment]
that is a patcher problem. Till then Change Sources to Inotia00 that will work fine

**Comment by mesofranico** [comment]
But the Inotia00 patcher only works for YouTube and YouTube Music, what about the rest of the applications?

**Comment by decipher3114** [comment]
> But the Inotia00 patcher only works for YouTube and YouTube Music, what about the rest of the applications?

bcz he only included those apps

**Comment by decipher3114** [comment]
Also, I am also build youtube with these patches and they are working fine..
